### ISSUE TITLE
datetime.timedelta.total_seconds object has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by commandtab** [fengsp/flask-session#10]
I'm attempting to run Flask-Session 0.1.1 under Python 2.6.6, and am running into an issue right around [this line](https://github.com/fengsp/flask-session/blob/master/flask_session/sessions.py#L147) (and others, if I was using those session storage methods):

```python
 File "/var/www/appname/venv/lib/python2.6/site-packages/flask_session/sessions.py", line 118, in save_session
   int(app.permanent_session_lifetime.total_seconds()))
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'
```

It seems that `datetime.timedelta.total_seconds` was [added in Python 2.7](https://docs.python.org/2/library/datetime.html#datetime.timedelta.total_seconds).

Is there by chance a 2.6-compatible drop-in replacement you'd consider?

Thanks!

**Comment by fengsp** [comment]
Thanks, noticed, I will fix it.
