### ISSUE TITLE
Maintenance of the project

### ISSUE THREAD

**Issue by dmtzs** [fengsp/flask-session#147]
Are there plans to keep mantaining the library? maybe @fengsp you should pass or invite to have ownership another people to mantain the library because there are many PR and issues raised, this library has so much potential so can we give more ownership to people interested in mantain this library?

**Comment by fengsp** [comment]
Duplicated with #156

**Comment by davidism** [comment]
Flask-Session is now part of Pallets-Eco, an open source organization managed by the Pallets team to facilitate community maintenance of Flask extensions. Anyone interested in helping maintain this project can ask for commit access in the `#flask-session` channel on https://discord.gg/pallets.
