### ISSUE TITLE
SQLAlchemy backend creates an incredible number of table entries

### ISSUE THREAD

**Issue by jschneier** [fengsp/flask-session#25]
I have a maximum of 30 or 50 users (the same users always) using my platform on any given day and I currently (after a couple weeks) have 90k+ entries in my SQLAlchemy table. What creates so many and why are they there, I believe I am using only default configurations.

**Comment by fengsp** [comment]
By default, all non-null sessions in Flask-Session are permanent.  What this means is that every request that doesn't support cookie will generate an entry, crawlers might be the reason for it.
