### ISSUE TITLE
Should not always set session.permanent = True

### ISSUE THREAD

**Issue by kilnyy** [fengsp/flask-session#4]
In sessions.py, Class ServerSideSession, you set session.permanent = True by default, but flask set session.permanent = False by default.

**Comment by fengsp** [comment]
If you set session.permanent to `False`, once you leave your browser, your session cookie will be gone, which is really not what we want.

**Comment by kilnyy** [comment]
The problem is that I think this should be controll by Flask itself. Extension should not change the default settings of Flask.

For most visitors of website, maybe they will not come back again. I think do not save the session of then is the better.

If one developer just drop in this extension, and do not know this extension change this settiing, it may cause lots of unused sessions saved in server.

**Comment by fengsp** [comment]
Actually not, these values are there for extensions to customize, and the change of this setting is documented in Flask-Session.

**Comment by fengsp** [comment]
If necessary, we could add one more config value to control the behavior :)

**Comment by kilnyy** [comment]
Oh, I did not read the document carefully, it is my fault ,so if you want you can add one more config.

Thank you
