### ISSUE TITLE
Handling exceptions

### ISSUE THREAD

**Issue by pors** [fengsp/flask-session#45]
Hi!

How could one handle exceptions with flask-session? When using SESSION_TYPE='redis' and redis is not available for some reason I can't find a way to catch the `redis.exceptions.ConnectionError` exception.

Any ideas how to do this?

Thanks for this awesome extension!

**Comment by fengsp** [comment]
That should be handled by the Flask, try http://flask.pocoo.org/docs/0.11/errorhandling/
