### ISSUE TITLE
Using Socket for Redis Session

### ISSUE THREAD

**Issue by kphretiq** [fengsp/flask-session#48]
Apparently setting
`SESSION_REDIS = "/var/run/redis/redis.sock"`
. . . does not produce magic. 

``` bash
  File "/home/user/Projects/foo/venv/lib/python2.7/site-packages/flask_session/sessions.py", line 131, in open_session
    val = self.redis.get(self.key_prefix + sid)
AttributeError: 'str' object has no attribute 'get'
```

Am I missing something obvious, or are you not supporting using a socket for redis sessions at this point?

**Comment by fengsp** [comment]
Read the docs and you will find the right way to do it, `SESSION_REDIS` should be a `redis.Redis` instance.
