### ISSUE TITLE
Change flask.ext.session to flask_session in imports

### ISSUE THREAD

**Issue by mcrowson** [fengsp/flask-session#59]
From: http://flask.pocoo.org/docs/0.12/extensiondev/ 

As of Flask 0.11, most Flask extensions have transitioned to the new naming schema. The flask.ext.foo compatibility alias is still in Flask 0.11 but is now deprecated – you should use flask_foo.

**Comment by romeojulietthotel** [comment]
https://github.com/fengsp/flask-session/pull/49

**Comment by fengsp** [comment]
Fixed in #49
