### ISSUE TITLE
Push updated docs to pythonhosted.org/Flask-Session

### ISSUE THREAD

**Issue by saschat** [fengsp/flask-session#88]
Those docs still say to `from flask.ext.session import Session` which clearly does not match the docs in this repo.

**Comment by reebr** [comment]
I believe this project is not maintained anymore.
I've replaced flask-session in favor of [#session](http://flask.pocoo.org/docs/1.0/quickstart/#sessions).

**Comment by saschat** [comment]
@reebr `flask-session` does not replace `sessions` from Flask but allows you to use different backends such as Memcached or Redis with `sessions`.

**Comment by saschat** [comment]
@yrro I would say it is the other way around ;-)
