### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by cmabastar** [fengsp/flask-session#9]
Hello,

Do you have any examples for redis support? It seems to be not working and base on the code it doesn't connect to the settings specified (url, key) etc..

**Comment by fengsp** [comment]
Could you show me your code?

**Comment by LynnCo** [comment]
I just came here for the same issue, then went back to the docs and saw that SESSION_REDIS is supposed to be a redis.Redis instance. Apparently eyes glazed over that part the first few times I read the docs?

**Comment by LynnCo** [comment]
So it might help to change the docs to have this, for the sake of poor readers such as myself

    import os
    from flask import Flask, session
    from flask.ext.session import Session
    from redis import Redis
    
    app = Flask(__name__)
    # Check Configuration section for more details
    SESSION_TYPE = 'redis'
    SESSION_REDIS = Redis(os.environ['REDISTOGO_URL'])
    app.config.from_object(__name__)
    Session(app)
