### ISSUE TITLE
Upgrading to werkzeug 0.15.1 causes warnings

### ISSUE THREAD

**Issue by insacuri** [fengsp/flask-session#99]
When running our unit tests, the following warning is being shown.  This was caused by upgrading Werkzeug to 0.15.2 from 0.14.1.

 ```<redacted>/python3.6/site-packages/flask_session/sessions.py:313: DeprecationWarning: 'werkzeug.contrib.cache' is deprecated as of version 0.15 and will be removed in version 1.0. It has moved to https://github.com/pallets/cachelib.```

**Comment by rayluo** [comment]
FYI: I encounter same problem, and I [fixed it in my fork](https://github.com/rayluo/flask-session/pull/1/files), and you can [install it in this way](https://github.com/rayluo/flask-session#how-to-install).

**Comment by fengsp** [comment]
Fixed since `0.3.2`.
